//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productform
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Productform
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Item Name required")]
        [StringLength(50, ErrorMessage = "Item name cannot exceed 50 characters")]
        [Remote("IsItemnameAvailable", "Productform", ErrorMessage ="ItemName is Use..")]
        public string ItemName { get; set; }
        [Required(ErrorMessage = "Item Price required")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Price should only contain numbers.")]
        [StringLength(5, ErrorMessage = "price should have a maximum length of 5.")]
        public Nullable<int> ItemPrice { get; set; }
        [Required(ErrorMessage = "Item image is required.")]
        [DataType(DataType.Upload)]
        [FileExtensions(Extensions = "jpg,jpeg.png,gif", ErrorMessage = "only image file are allowed.")]
        public string ItemImage { get; set; }
    }
}
